{
 "title": "ENTRADA - DNS Statistics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "NS", "label": "Name server", "query": "entrada.dns.query.ns.*" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<h1 style=\"text-align: center;\" markdown=\"1\">DNS statistics</h1>"
  },
  {
   "title": "Queries",
   "type": "graph",
   "description": "Queries per 10-second bucket",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(entrada.dns.query.ns.$NS, 4)"
    }
   ]
  },
  {
   "title": "Top 10 countries",
   "type": "graph",
   "description": "Top-10 countries based on source IP-address",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(limit(sortByTotal(entrada.geo.country.*.ns.$NS), 10), 3)"
    }
   ]
  },
  {
   "title": "Query origin",
   "type": "grafana-worldmap-panel",
   "description": "Geographical location based on source IP-address",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 11 },
   "valueName": "total",
   "targets": [
    {
     "target": "aliasByNode(minimumAbove(consolidateBy(entrada.geo.country.*.ns.$NS, 'average'), 0), 3)"
    }
   ]
  },
  {
   "title": "Qtype",
   "type": "graph",
   "description": "The 10 most used qtypes",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(limit(sortByTotal(entrada.dns.request.qtype.*.ns.$NS), 10), 4)"
    }
   ]
  },
  {
   "title": "Rcode",
   "type": "graph",
   "description": "Rcodes per 10-second bucket",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(entrada.dns.request.rcode.*.ns.$NS, 4)"
    }
   ]
  },
  {
   "title": "Opcode",
   "type": "graph",
   "description": "Opcodes per 10-second bucket",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(entrada.dns.request.opcode.*.ns.$NS, 4)"
    }
   ]
  },
  {
   "title": "TCP RTT",
   "type": "graph",
   "description": "Median TCP RTT for handshake and stream packets",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ms", "label": "RTT" }
   ],
   "targets": [
    {
     "target": "alias(entrada.tcp.rtt.handshake.median.ns.$NS, 'Handshake')"
    },
    {
     "target": "alias(entrada.tcp.rtt.packet.median.ns.$NS, 'Packet')"
    }
   ]
  },
  {
   "title": "Transport protocol",
   "type": "graph",
   "description": "Transport protocol used",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(entrada.tcp.ns.$NS, 'TCP')"
    },
    {
     "target": "alias(entrada.udp.ns.$NS, 'UDP')"
    }
   ]
  }
 ]
}