{
 "title": "ENTRADA 2.0 DNS Performance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "NS", "label": "Name server", "query": "entrada.dns.query.ns.*" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<h1 style=\"text-align: center;\" markdown=\"1\">DNS Performance</h1>"
  },
  {
   "title": "Query Location",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 3 },
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(minimumAbove(consolidateBy(entrada.geo.country.*.ns.$NS, 'average'), 0), 3)"
    }
   ]
  },
  {
   "title": "TCP RTT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(entrada.tcp.rtt.handshake.median.ns.$NS, 'Handshake')"
    },
    {
     "target": "alias(entrada.tcp.rtt.packet.median.ns.$NS, 'Packet')"
    }
   ]
  },
  {
   "title": "TCP Samples",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(entrada.tcp.rtt.packet.samples.ns.$NS, 'Samples')"
    }
   ]
  },
  {
   "title": "Transport protocol",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(entrada.tcp.ns.$NS, 'TCP')"
    },
    {
     "target": "alias(entrada.udp.ns.$NS, 'UDP')"
    }
   ]
  }
 ]
}