CREATE EXTERNAL TABLE IF NOT EXISTS DATABASE.queries (
  `id` int,
  `unixtime` bigint,
  `time` bigint,
  `qname` string,
  `domainname` string,
  `len` int,
  `frag` int,
  `ttl` int,
  `ipv` int,
  `prot` int,
  `src` string,
  `srcp` int,
  `dst` string,
  `dstp` int,
  `udp_sum` int,
  `dns_len` int,
  `aa` boolean,
  `tc` boolean,
  `rd` boolean,
  `ra` boolean,
  `z` boolean,
  `ad` boolean,
  `cd` boolean,
  `ancount` int,
  `arcount` int,
  `nscount` int,
  `qdcount` int,
  `opcode` int,
  `rcode` int,
  `qtype` int,
  `qclass` int,
  `country` string,
  `asn` string,
  `edns_udp` int,
  `edns_version` smallint,
  `edns_do` boolean,
  `edns_ping` boolean,
  `edns_nsid` string,
  `edns_dnssec_dau` string,
  `edns_dnssec_dhu` string,
  `edns_dnssec_n3u` string,
  `edns_client_subnet` string,
  `edns_other` string,
  `edns_client_subnet_asn` string,
  `edns_client_subnet_country` string,
  `labels` int,
  `res_len` int,
  `svr` string,
  `time_micro` bigint,
  `resp_frag` int,
  `proc_time` int,
  `is_google` boolean,
  `is_opendns` boolean,
  `dns_res_len` int,
  `server_location` string,
  `edns_padding` int,
  `pcap_file` string,
  `edns_keytag_count` int,
  `edns_keytag_list` string,
  `q_tc` boolean,
  `q_ra` boolean,
  `q_ad` boolean,
  `q_rcode` int
) PARTITIONED BY (
  year int,
  month int,
  day int,
  server string
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = '1'
) LOCATION 's3://BUCKET/queries/'
TBLPROPERTIES ('has_encrypted_data'='false')
