package nl.sidnlabs.entrada.model;

// ENUM for fast access to the index of a avro record field, this saves an additional looklup to
// find index for field name.
public enum FieldEnum {
  // make sure the order of fields matches the order used in dns-query.avsc schema
  id,
  time,
  qname,
  domainname,
  frag,
  ttl,
  ipv,
  prot,
  src,
  srcp,
  dst,
  dstp,
  aa,
  tc,
  rd,
  ra,
  z,
  ad,
  cd,
  ancount,
  arcount,
  nscount,
  qdcount,
  opcode,
  rcode,
  qtype,
  qclass,
  country,
  asn,
  asn_organisation,
  edns_udp,
  edns_version,
  edns_do,
  edns_ping,
  edns_nsid,
  edns_dnssec_dau,
  edns_dnssec_dhu,
  edns_dnssec_n3u,
  edns_client_subnet,
  edns_other,
  edns_client_subnet_asn,
  edns_client_subnet_asn_organisation,
  edns_client_subnet_country,
  labels,
  resp_frag,
  proc_time,
  server_location,
  edns_padding,
  pcap_file,
  edns_keytag_count,
  edns_keytag_list,
  q_tc,
  q_ra,
  q_ad,
  pub_resolver,
  req_len,
  res_len,
  tcp_hs_rtt,
  req_ip_df,
  res_ip_df;
}
