package nl.sidn.dnslib.logic.openssl.wrapper;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : openssl-1.0.1e/crypto/crypto.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("libcrypto") 
public class CRYPTO_THREADID extends StructObject {
	/** C type : void* */
	@Field(0) 
	public Pointer<? > ptr() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : void* */
	@Field(0) 
	public CRYPTO_THREADID ptr(Pointer<? > ptr) {
		this.io.setPointerField(this, 0, ptr);
		return this;
	}
	@CLong 
	@Field(1) 
	public long val() {
		return this.io.getCLongField(this, 1);
	}
	@CLong 
	@Field(1) 
	public CRYPTO_THREADID val(long val) {
		this.io.setCLongField(this, 1, val);
		return this;
	}
	public CRYPTO_THREADID() {
		super();
	}
	public CRYPTO_THREADID(Pointer pointer) {
		super(pointer);
	}
}
